-- CreateTable
CREATE TABLE `User` (
    `USER_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `VISITOR_NO` VARCHAR(191) NOT NULL,
    `FULL_NAME` VARCHAR(191) NOT NULL,
    `ID_CARD_NO` VARCHAR(191) NOT NULL,
    `COMPANY_NAME` VARCHAR(191) NOT NULL,
    `LICENSE_PLATE` VARCHAR(191) NOT NULL,
    `PURPOSE` VARCHAR(191) NOT NULL,
    `MEET_WITH` VARCHAR(191) NOT NULL,
    `SELFIE_PHOTO_URL` VARCHAR(191) NOT NULL,
    `ID_CARD_PHOTO_URL` VARCHAR(191) NOT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    PRIMARY KEY (`USER_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
